In [32]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
df_train = pd.read_csv("D:\ml data sets\mobile_price_classification_train.csv")
df_test = pd.read_csv("D:\ml data sets\mobile_price_classification_test.csv")

In [34]:
df_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [35]:
df_test.head()

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   
1   2            841     1          0.5         1   4       1          61   
2   3           1807     1          2.8         0   1       0          27   
3   4           1546     0          0.5         1  18       1          25   
4   5           1434     0          1.4         0  11       1          49   

   m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193  ...  16        226      1412  3476    12     7   
1    0.8        191  ...  12        746       857  3895     6     0   
2    0.9        186  ...   4       1270      1366  2396    17    10   
3    0.5         96  ...  20        295      1752  3893    10     0   
4    0.5        108  ...  18        749       810  1773    15     8   

   talk_time  three_g  touch_screen  wifi  
0          2        0             1     0  
1          7        1             0     0  
2         10        0             1     1  
3          7        1             1     0  
4          7        1             0     1  

[5 rows x 21 columns]

In [36]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
battery_power    2000 non-null int64
blue             2000 non-null int64
clock_speed      2000 non-null float64
dual_sim         2000 non-null int64
fc               2000 non-null int64
four_g           2000 non-null int64
int_memory       2000 non-null int64
m_dep            2000 non-null float64
mobile_wt        2000 non-null int64
n_cores          2000 non-null int64
pc               2000 non-null int64
px_height        2000 non-null int64
px_width         2000 non-null int64
ram              2000 non-null int64
sc_h             2000 non-null int64
sc_w             2000 non-null int64
talk_time        2000 non-null int64
three_g          2000 non-null int64
touch_screen     2000 non-null int64
wifi             2000 non-null int64
price_range      2000 non-null int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB


In [37]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
id               1000 non-null int64
battery_power    1000 non-null int64
blue             1000 non-null int64
clock_speed      1000 non-null float64
dual_sim         1000 non-null int64
fc               1000 non-null int64
four_g           1000 non-null int64
int_memory       1000 non-null int64
m_dep            1000 non-null float64
mobile_wt        1000 non-null int64
n_cores          1000 non-null int64
pc               1000 non-null int64
px_height        1000 non-null int64
px_width         1000 non-null int64
ram              1000 non-null int64
sc_h             1000 non-null int64
sc_w             1000 non-null int64
talk_time        1000 non-null int64
three_g          1000 non-null int64
touch_screen     1000 non-null int64
wifi             1000 non-null int64
dtypes: float64(2), int64(19)
memory usage: 164.1 KB


In [38]:
X_ = df_train.drop(["price_range"],axis=1)
X_train = X_.iloc[0:1500,:]
X_val = X_.iloc[1500:,:]
y_ = df_train["price_range"]
y_train = y_.iloc[0:1500]
y_val = y_.iloc[1500:]
X_test = df_test.drop(["id"],axis=1)
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)
print(X_test.shape)


(1500, 20)
(1500,)
(500, 20)
(500,)
(1000, 20)


In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train.astype(np.float64))
X_val_std = scaler.fit_transform(X_val.astype(np.float64))
X_test_std = scaler.fit_transform(X_test.astype(np.float64))


In [40]:
X_train_std

array([[-0.9084276 , -0.96720415,  0.83253881, ..., -1.76660101,
        -1.02020406,  0.968496  ],
       [-0.50083088,  1.03390789, -1.25207821, ...,  0.56605877,
         0.98019606, -1.03252879],
       [-1.543732  ,  1.03390789, -1.25207821, ...,  0.56605877,
         0.98019606, -1.03252879],
       ...,
       [ 0.30525428, -0.96720415,  1.69091053, ...,  0.56605877,
        -1.02020406,  0.968496  ],
       [-0.81962161, -0.96720415, -0.63895555, ...,  0.56605877,
         0.98019606,  0.968496  ],
       [ 1.14094142,  1.03390789, -1.25207821, ...,  0.56605877,
         0.98019606, -1.03252879]])

In [41]:
X_val_std

array([[-0.01419233, -1.06191317, -1.01114584, ...,  0.54036068,
        -0.96462528, -0.96076892],
       [ 1.68024472,  0.94169658, -1.25603463, ...,  0.54036068,
         1.03667198,  1.040833  ],
       [-0.10289441,  0.94169658, -1.25603463, ...,  0.54036068,
        -0.96462528, -0.96076892],
       ...,
       [ 1.5460544 , -1.06191317, -0.76625704, ...,  0.54036068,
         1.03667198, -0.96076892],
       [ 0.63856395, -1.06191317, -0.76625704, ...,  0.54036068,
         1.03667198,  1.040833  ],
       [-1.64039702,  0.94169658,  0.58063133, ...,  0.54036068,
         1.03667198,  1.040833  ]])

In [42]:
X_test_std

array([[-0.47545131,  0.968496  ,  0.31260069, ..., -1.76021608,
         1.        , -1.01409939],
       [-0.94278218,  0.968496  , -1.25583195, ...,  0.56811207,
        -1.        , -1.01409939],
       [ 1.29207729,  0.968496  ,  1.51908734, ..., -1.76021608,
         1.        ,  0.98609664],
       ...,
       [-0.1469316 , -1.03252879, -0.16999397, ...,  0.56811207,
        -1.        , -1.01409939],
       [ 0.65817305,  0.968496  , -1.25583195, ..., -1.76021608,
         1.        , -1.01409939],
       [ 0.04971753,  0.968496  , -1.25583195, ...,  0.56811207,
        -1.        ,  0.98609664]])

In [43]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y_train_bin = lb.fit_transform(y_train)
y_val_bin = lb.fit_transform(y_val)
y_train_bin = y_train_bin[:,0]
y_val_bin = y_val_bin[:,0]


In [44]:
no_of_features = 20
hl_1 = 100
hl_2 = 80
hl_3 = 50
ol = 2

In [45]:
X = tf.placeholder(tf.float32,shape = (None,no_of_features))
y = tf.placeholder(tf.int64,shape = (None))

In [46]:

# def neuron_layer(X,n_neuron,name,distribution = "normal",activation = None):
#     with tf.name_scope(name):
#         n_input =  int(X.get_shape()[1])
#         std = 2/np.sqrt(n_input)
#         if distribution == "normal":
#             init = tf.truncated_normal((n_input,n_neuron),stddev = std)
#         elif distribution == "uniform":
#             init = tf.random.uniorm((n_input,n_neuron),stddev=std)
            
#         W= tf.get_variable(initializer=init,name = "weight",regularizer=tf.contrib.layers.l2_regularizer(scale=0.1))
#         tf.add_to_collection(tf.GraphKeys.REGULARIZATION_LOSSES, W)
#         b = tf.Variable(tf.zeros([n_neuron]),name ="biases")
#         Z = tf.matmul(X,W)+b
#         if activation == "relu":
#             return tf.nn.relu(Z)
             
#         elif activation == "leaky_relu":
#             return tf.maximum(0.01*Z,Z)
        
#         elif activation == "elu":
#             return tf.nn.elu(Z)
            
#         elif activation == "logistic":
#             return tf.nn.sigmoid(Z)
            
           
#         else: 
#             return Z

In [47]:
#batch norm implementation
from tensorflow.contrib.layers import batch_norm
is_training_batch = tf.placeholder(tf.bool, shape=(), name='is_training_batch')
bn_params = {
'is_training': is_training_batch,
'decay': 0.99,
'updates_collections': None
}

In [48]:
# Drop out implementation
from tensorflow.contrib.layers import dropout
is_training_drop = tf.placeholder(tf.bool,shape=(),name="is_training_drop")
keep_prob=0.8
X_drop = dropout(X,keep_prob,is_training = is_training_drop)

In [49]:
#drop out implementation
# with tf.name_scope("DNN"):
#     hlayer1 = neuron_layer(X_drop,hl_1,"hiddenlayer1",distribution="normal",activation="elu")
#     hlayer1_drop = dropout(hlayer1,keep_prob,is_training=is_training)
#     hlayer2 = neuron_layer(hlayer1_drop,hl_2,"hiddenlayer2",distribution = "normal",activation="elu")
#     hlayer2_drop = dropout(hlayer2,keep_prob,is_training=is_training)
#     output = neuron_layer(hlayer2_drop,ol,"outputlayer")
    


In [50]:
from tensorflow.contrib.layers import fully_connected
with tf.name_scope("MODEL"):
    with tf.contrib.framework.arg_scope([fully_connected],normalizer_fn=batch_norm,normalizer_params=bn_params):
        hlayer1 = fully_connected(X_drop,hl_1,activation_fn=tf.nn.elu,weights_initializer=tf.contrib.layers.variance_scaling_initializer())
        hlayer1_drop = dropout(hlayer1,keep_prob,is_training=is_training_drop)
        hlayer2 = fully_connected(hlayer1_drop,hl_2,activation_fn=tf.nn.elu,weights_initializer=tf.contrib.layers.variance_scaling_initializer())
        hlayer2_drop = dropout(hlayer2,keep_prob,is_training=is_training_drop)
        output = fully_connected(hlayer2_drop,ol)


In [51]:
with tf.name_scope("LOSS"):
    entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,logits=output)
    loss = tf.reduce_mean(entropy,name ="loss")

In [52]:
learning_rate = 0.01
with tf.name_scope("TRAIN"):
    optimizer = tf.train.AdamOptimizer(learning_rate)
    training_op = optimizer.minimize(loss)

In [53]:
with tf.name_scope("EVAL"):
    y_pred = tf.cast(tf.argmax(output, axis=1), tf.int64)
    matched = tf.equal(y_pred, y)
    accuracy = tf.reduce_mean(tf.cast(matched, tf.float32))

#     correct = tf.nn.in_top_k(output, y, 1)
#     accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

In [54]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [68]:
# from datetime import datetime
# now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
# root_logdir = "tf_logs"
# logdir = "{}/run-{}/".format(root_logdir, now)

# tf.summary.scalar('MSE', loss)
# tf.summary.scalar('MSE', accuracy)

n_epochs = 100
batch_size = 50
with tf.Session() as sess:
    sess.run(init)
    file_writer = tf.summary.FileWriter(logdir, sess.graph)
    for epoch in range(n_epochs):
        for j in range(int(1500/batch_size)):
            X_batch_train,y_batch_train = X_train_std[j*batch_size:(j+1)*batch_size,:],y_train_bin[j*batch_size:(j+1)*batch_size]
#             merged_summary_op = tf.summary.merge_all()
            _= sess.run([training_op],feed_dict={X:X_batch_train,y:y_batch_train,is_training_batch:True,is_training_drop:True})
#             summary= sess.run([merged_summary_op],feed_dict={X:X_batch_train,y:y_batch_train})
#             if(j%10==0):
#                 file_writer.add_summary(summary, epoch * 30 + j)
        if(epoch%10==0):
            acc_train = accuracy.eval(feed_dict = {X:X_batch_train,y:y_batch_train,is_training_batch:False,is_training_drop:False})
            save_path = saver.save(sess, "D:\ml data sets\my_model_final.ckpt")
            print(epoch, "Train accuracy:", acc_train)
        if(epoch==99):
            acc_train = accuracy.eval(feed_dict = {X:X_batch_train,y:y_batch_train,is_training_batch:False,is_training_drop:False})
            print(epoch, "Train accuracy:", acc_train)    
    sess.run(training_op,feed_dict={X:X_val_std,y:y_val_bin,is_training_batch:True,is_training_drop:True})    
    acc_val = accuracy.eval(feed_dict = {X:X_val_std,y:y_val_bin,is_training_batch:False,is_training_drop:False})
    print("validation accuracy",acc_val)
    save_path = saver.save(sess, "D:\ml data sets\my_model_final.ckpt")
#     sess.run(training_op,feed_dict={X:X_Test})    
file_writer.close()

0 Train accuracy: 0.72
10 Train accuracy: 1.0
20 Train accuracy: 0.98
30 Train accuracy: 1.0
40 Train accuracy: 1.0
50 Train accuracy: 1.0
60 Train accuracy: 0.98
70 Train accuracy: 0.98
80 Train accuracy: 0.98
90 Train accuracy: 0.96
99 Train accuracy: 0.98
validation accuracy 0.94


In [69]:
with tf.Session() as sess:
    saver.restore(sess, "D:\ml data sets\my_model_final.ckpt")
    Z = output.eval(feed_dict={X: X_test_std,is_training_batch:False,is_training_drop:False})
    y_pred = np.argmax(Z, axis=1)
    print(y_pred)

INFO:tensorflow:Restoring parameters from D:\ml data sets\my_model_final.ckpt
[0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0
 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1
 0 0 0 0 1 0 0 1 0 0 1